### ISSUE TITLE
integration_tests broken at head

### ISSUE THREAD

**Issue by ThomasColthurst** [probcomp/hierarchical-irm#108]
As of commit 98fa59a, two of the integration tests fail.  First, test_misc fails with

logsumexp is 0.00
test_misc: util_io.cc:481: std::map<std::__cxx11::basic_string<char>, std::map<int, std::vector<std::__cxx11::basic_string<char> > > > load_clusters_irm(const std::string&): Assertion `items.size() > 0' failed.

And
./bazel-bin/hirm --iters=5 --load=assets/animals.unary.1.hirm assets/animals.unary
fails with
loading clusters from assets/animals.unary.1.hirm
hirm: util_io.cc:558: ... load_clusters_hirm(const std::string&): Assertion `irmc > -1' failed.

**Comment by ThomasColthurst** [comment]
Re-assigning to Srinivas because #105 is the most likely suspect, given that the integration tests pass at #102, the previously merged pull request.

**Comment by srvasude** [comment]
Fixed by #115 . I found a bug in `test_hirm_animals` from some other changes but that's accounted for.

Also added a workflow for this
