### ISSUE TITLE
Add a test utility similar to `run_test_sample_consistent_log_prob` in TFP

### ISSUE THREAD

**Issue by emilyfertig** [probcomp/hierarchical-irm#122]
This will be used to test the consistency of `sample` and `logp` for simple distributions and emissions.

From the TFP docs:
```
    The idea of this test is to compute the Monte-Carlo estimate of the volume
    enclosed by a hypersphere, i.e., the volume of an `n`-ball. While we could
    choose an arbitrary function to integrate, the hypersphere's volume is nice
    because it is intuitive, has an easy analytical expression, and works for
    `dimensions > 1`.
```

**Comment by srvasude** [comment]
Mentioned this to Emily that because a lot of the distributions are discrete, we can actually get away with checking pmfs approximately match (and for the normal distribution check moments as a heuristic test for now, adding something more complicated if need be). #184 fixed this.
