### ISSUE TITLE
pclean crashes while transitioning latent values (during inference)

### ISSUE THREAD

**Issue by ThomasColthurst** [probcomp/hierarchical-irm#147]
Run run with

./bazel-bin/pclean/pclean --schema=assets/flights.schema --obs=assets/flights_dirty.10.csv --iters=5

the program crashes with

terminate called after throwing an instance of 'std::out_of_range'
  what():  unordered_map::at

The approximate call stack is

pclean/pclean
inference.cc::inference_hirm
hirm.cc:transition_latent_values_relation (on relation "Time:time")
transition_latent_value.hh:transition_latent_value (on value ":")
transition_latent_value.hh:unincorporate_and_store_values
in the noisy_relations for loop with noisy_relation = act_dep_time
with
rel->base_to_noisy_items.at(base_items)
being the offending unordered_map::at call.

**Comment by ThomasColthurst** [comment]
A little more debugging info:  the keys of rel->base_to_noisy_items are [0], [1], [3], [4], [6], [7], and [8] when the crash happens, and the base_items being looked up is [5].

The base_to_noisy_items seems correct here, since in the flights_dirty.10.csv file, the act_dep_time field is missing on the 2-nd and 5-th lines of data (using 0 based counting).

**Comment by emilyfertig** [comment]
Thanks for digging into this, I'll send a fix later today.
