### ISSUE TITLE
pclean crashes on rent and flights data

### ISSUE THREAD

**Issue by ThomasColthurst** [probcomp/hierarchical-irm#152]
both while transitioning the IRMs, with the same failure 

pclean: clean_relation.hh:300: double CleanRelation<T>::logp_gibbs_exact_variant(const Domain&, const T_item&, int, const std::vector<std::vector<int> >&, std::mt19937*) [with T = std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >; T_item = int; std::mt19937 = std::mersenne_twister_engine<long unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>]: Assertion `abs(cluster->logp_score() - logp0) <= std::numeric_limits<double>::epsilon() * abs(logp0)' failed.

**Comment by ThomasColthurst** [comment]
+ Srinivas because Emily said you added this check recently.

**Comment by srvasude** [comment]
FWIW, this check is a relaxation of the previous check of (cluster->logp_score() == logp0). That checks that after doing all the adding and removals (for computing the logp of the result of transitioning) that we didn't change the logp too much. If this becomes more of a problem, we need to either rethink the Gibbs strategy and/or make the underlying distributions more numerically robust to these combinations of floating point operations.
