### ISSUE TITLE
`util_io_test.cc` is failing at head

### ISSUE THREAD

**Issue by emilyfertig** [probcomp/hierarchical-irm#153]
It looks like it might be a problem with `load_schema`.

```
==================== Test output for //:util_io_test:
Running 7 test cases...
util_io_test.cc(11): error: in "test_nary_relation": check schema.contains("R1") has failed
util_io_test.cc(15): error: in "test_nary_relation": check R1.domains.size() == 1 has failed [0 != 1]
unknown location(0): fatal error: in "test_nary_relation": memory access violation at address: 0x0: no mapping at fault address
util_io_test.cc(16): last checkpoint

*** 3 failures are detected in the test module "test UtilIO"
================================================================================
```

**Comment by emilyfertig** [comment]
Assigning to @ThomasColthurst since this started failing at f403b1f4905b6defa0c499c17a33f017fce2c844

**Comment by ThomasColthurst** [comment]
I am unable to reproduce this -- when I check out master, all the tests including util_io_test pass for me.

GitHub runs all of the unit tests on every pull request and recent pull requests show util_io_test passing.  For example, https://github.com/probcomp/hierarchical-irm/actions/runs/10358826098/job/28673884093?pr=155

**Comment by emilyfertig** [comment]
Are you compiling in `opt` or `dbg` mode? It's failing for me with `opt` but I just tried `dbg` and it passed.

**Comment by ThomasColthurst** [comment]
Neither; I'm just running bazel test without any additional arguments (and I believe GitHub does the same).

**Comment by ThomasColthurst** [comment]
I can reproduce the failure when running with -c opt.  Interestingly, schema_helper_test also fails with -c opt, and we get a large number of additional warnings as well.
