### ISSUE TITLE
Write Python scripts to generate simple synthetic datasets/HIRM schemas

### ISSUE THREAD

**Issue by emilyfertig** [probcomp/hierarchical-irm#159]
These can live in `cxx/assets/test_files` and be patterned on the files already there. They can use the HIRM-like/Model 4 schema and observation formats (as opposed to the PClean-like format introduced in Model 5). The synthetic datasets are described in Section 4.2 of the overleaf and are as follows:

- [x] Single column data: numerical
- [x] Single column data: strings
- [x] Multi-column data
- [x] CrossCat data for each datatype (section 4.3.1):
  - [x] Float
  - [x] Categorical
  - [x] String
  - [x] Boolean

Please check the box when beginning work on any of these.

**Comment by srvasude** [comment]
FWIW we have some of this along with the associated scripts.

**Comment by emilyfertig** [comment]
@srvasude thanks, could you check off the ones that are done or in progress?
