### ISSUE TITLE
Update the schema and ingestion code to support noisy relations

### ISSUE THREAD

**Issue by emilyfertig** [probcomp/hierarchical-irm#53]
Need to specify which relations/observations are noisy

**Comment by ThomasColthurst** [comment]
What do you think about moving the model 4 hirm schema to look a bit more like PClean class variable declarations?  Something like:

R1 ~ bernoulli(D1)
R3 ~ bigram(D2)
R6 ~ normal(D1)
R2 ~ gaussian(R6; D1, D2)
R4 ~ gaussian(R2; D1, D2, D3)
R5 ~ sometimes_bitflip(R1, D1)

The primary benefit would be readability; "R6 ~ normal(D1)" is IMHO a lot more understandable than "clean normal R6 D1".  But having the same syntax between the two schemas would also help lower cognitive barriers to entry (and perhaps even allow some code reuse).

**Comment by ThomasColthurst** [comment]
Yep!  I'm planning on basing the Model 5 schema pretty heavily on PClean.

**Comment by emilyfertig** [comment]
Cool, I'll update #95

**Comment by emilyfertig** [comment]
I didn't get to #95 today -- let me know if you'd rather take it over, since you're owning the schema stuff and probably have a better sense of how it fits with Model 5 and where/how code can be reused. Otherwise I'll try to do it tomorrow.

**Comment by ThomasColthurst** [comment]
I could take over #95 if you like.  The schema will have to be slightly different, because HIRM relations are (in the schema) conditioned on domains and PClean class variables aren't.  But some the parsing code could be shared.

**Comment by emilyfertig** [comment]
Thank you, I'd appreciate that!
