### ISSUE TITLE
Enable `Distribution` to explicitly represent latents instead of marginalizing, and implement logp/logp_score with fixed latents.

### ISSUE THREAD

**Issue by emilyfertig** [probcomp/hierarchical-irm#56]
First, we will need a way for a Distribution (our in-code representation
of a data model) to specify to the system whether it wants to explicitly
represent its latents, or collapse (marginalize) them.

• For distributions that explicitly represent their latents, logp score should
return the conditional likelihood of the accumulated data given the current
value of the parameter θ, and logp should return the likelihood of a new
datapoint x given θ

**Comment by ThomasColthurst** [comment]
Done in https://github.com/probcomp/hierarchical-irm/pull/67
