### ISSUE TITLE
Add `transition_theta` and `transition_hypers` in `Distribution` given explicit latents

### ISSUE THREAD

**Issue by emilyfertig** [probcomp/hierarchical-irm#57]
A new transition theta method (for distributions that explicitly repre-
sent their parameters) will perform an MCMC update on the parameter
θ, given the accumulated data. In the case of conjugate models, this could
sample from the exact conditional distribution of θ given the accumulated
data; in non-conjugate models, we might implement a Metropolis-Hastings
transition with an accept-reject step, or a Hamiltonian Monte Carlo tran-
sition if gradients are available.

The transition hypers method added in Model 2 will—for data models
that explicitly represent latents—need to be based on the current value of
θ, rather than the marginal likelihood of the accumulated data.

**Comment by ThomasColthurst** [comment]
Done in https://github.com/probcomp/hierarchical-irm/pull/69
