### ISSUE TITLE
README: Add Bazel distribution URI so `apt` can find it.

### ISSUE THREAD

**Issue by Schaechtle** [probcomp/hierarchical-irm#75]
Suggested edit to the README in the [C++ installation section](https://github.com/probcomp/hierarchical-irm?tab=readme-ov-file#installation-c): In order for `apt` to install bazel, one needs to add the Bazel distribution URI as a package source (see [here](https://bazel.build/install/ubuntu)).

**Comment by srvasude** [comment]
#106 fixes this
